# NumPy Exercises 

Write the code for the following questions in the space provided and submit the .ipynb files on Nalanda

#### Q 1: Import NumPy as np

In [3]:
import numpy as np

#### Q 2: Create an array of 10 zeros 

In [4]:
array0=np.zeros(10)
print(array0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Q 3: Create an array of 10 ones

In [5]:
array1=np.ones(10)
print(array1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Q 4: Create an array of 10 fives

In [6]:
array5=np.ones(10)*5
print(array5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Q 5: Create an array of the integers from 10 to 50

In [7]:
array=np.arange(10,51)
print(array) 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Q 6: Create an array of all the even integers from 10 to 50

In [8]:
array=np.arange(10,51,2)
print(array) 

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Q 7: Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
matrix =  np.arange(0, 9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Q 8: Create a 3x3 identity matrix

In [10]:
identity=np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Q 9: Use NumPy to generate a random number between 0 and 1

In [11]:
r = np.random.rand()
print(r)

0.05224222549585733


#### Q 10: Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [12]:
array25 = np.random.normal(0,1,25)
print(array25)

[-0.61307781  0.39497017 -1.01510365 -0.28751994  0.09272887 -0.18780227
  1.01313245  2.68959089 -1.68946932 -1.11669173  1.7470729  -0.90427782
  0.65047046  0.32007196  0.3928094   0.43439716  0.52588037  0.86758564
 -0.03546957  0.20646056 -0.73917984  0.10611947 -0.8285805  -0.07502296
  0.49243861]


#### Create the following matrix:

#### Q 11: Create an array of 20 linearly spaced points between 0 and 1:

In [13]:
array20=np.linspace(0, 1, 20)
print(array20)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection
Write the code to produce the given outputs using the matrix "mat" 

In [14]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [16]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[3,4]

20

In [17]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [18]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[4]

array([21, 22, 23, 24, 25])

In [23]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
mat[3::]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat

In [20]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [21]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [22]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])